# Generated by Django 5.2.6 on 2025-09-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='messages', through='core.AlertRecipient', to='core.parent'),
        ),
    ]
