# Generated by Django 5.2.7 on 2025-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecipient',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='provider_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
