# Generated by ChatGPT - add Hubtel fields to Organization
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orgalertrecipient_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hubtel_api_key',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hubtel_api_url',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hubtel_client_id',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='hubtel_client_secret',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
