# Generated by Django 5.2.7 on 2025-12-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contact_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
