# Generated by Django 5.2.7 on 2025-12-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_hubtel_fields'),
        ('core', '0015_org_admin_flags'),
    ]

    operations = [
    ]
