# Generated by ChatGPT - add hubtel_sender_id to Organization
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_0012_add_hubtel_fields_0015_org_admin_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hubtel_sender_id',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
    ]
