# Generated by Django 5.2.7 on 2025-12-13 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
