# Generated by Django 5.2.7 on 2025-12-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organization_balance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['status', 'sent_at'], name='core_alertr_status_b98b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['message', 'status'], name='core_alertr_message_59a534_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'created_at'], name='core_contac_organiz_8c6e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'phone_number'], name='core_contac_organiz_b67585_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['school', 'scheduled_time'], name='core_messag_school__42ddba_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['school', 'sent', 'created_at'], name='core_messag_school__88ee5c_idx'),
        ),
        migrations.AddIndex(
            model_name='orgalertrecipient',
            index=models.Index(fields=['status', 'sent_at'], name='core_orgale_status_5ce319_idx'),
        ),
        migrations.AddIndex(
            model_name='orgalertrecipient',
            index=models.Index(fields=['message', 'status'], name='core_orgale_message_b64255_idx'),
        ),
        migrations.AddIndex(
            model_name='orgalertrecipient',
            index=models.Index(fields=['contact', 'status'], name='core_orgale_contact_599573_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'onboarded'], name='core_organi_is_acti_083fab_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='core_organi_slug_517c11_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmessage',
            index=models.Index(fields=['organization', 'scheduled_time'], name='core_orgmes_organiz_5c2e36_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmessage',
            index=models.Index(fields=['organization', 'sent', 'created_at'], name='core_orgmes_organiz_ae5f42_idx'),
        ),
    ]
