# Generated by Django 5.2.7 on 2025-12-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_database_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS cache_table (
                cache_key VARCHAR(255) PRIMARY KEY,
                value TEXT NOT NULL,
                expires DATETIME NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS cache_table;"
        ),
    ]
