# Generated by Django 5.2.7 on 2025-12-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_create_cache_table'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS cache_table;
            CREATE TABLE cache_table (
                cache_key VARCHAR(255) PRIMARY KEY,
                value TEXT NOT NULL,
                expires TIMESTAMP NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS cache_table;"
        ),
    ]
