# Generated by Django 5.2.7 on 2025-12-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sms_count', models.PositiveIntegerField(help_text='Number of SMS included in the package')),
                ('expiry_days', models.PositiveIntegerField(default=0, help_text='Days until package expires (0 for non-expiry)')),
                ('package_type', models.CharField(choices=[('expiry', 'Expiry Package'), ('non_expiry', 'Non-Expiry Package')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='package_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sms_remaining',
            field=models.PositiveIntegerField(default=0, help_text='SMS remaining in current package'),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.package'),
        ),
    ]
