# Generated by Django 5.2.7 on 2025-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_package_organization_package_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium features enabled'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Grants premium features'),
        ),
    ]
