# Generated by Django 5.2.7 on 2025-12-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_organization_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsmstemplate',
            name='is_pre_built',
            field=models.BooleanField(default=False, help_text='Whether this is a pre-built template'),
        ),
    ]
