# Generated by Django 5.2.7 on 2025-12-14 16:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_orgsmstemplate_is_pre_built'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='current_package',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='package_expiry_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='sms_remaining',
        ),
        migrations.AddField(
            model_name='organization',
            name='sms_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.25'), help_text='Cost per SMS in cedis', max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_sms_sent',
            field=models.PositiveIntegerField(default=0, help_text='Total SMS sent by organization'),
        ),
    ]
