# Generated by Django 5.2.7 on 2025-12-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgalertrecipient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='orgalertrecipient',
            index=models.Index(fields=['is_deleted'], name='core_orgale_is_dele_c41fee_idx'),
        ),
    ]
