# Generated by Django 5.2.7 on 2025-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_orgalertrecipient_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sender_id',
            field=models.CharField(blank=True, help_text='Optional alphanumeric sender ID (requires approval)', max_length=50, null=True),
        ),
    ]
