# Generated by Django 5.2.7 on 2025-12-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_increase_sender_id_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sender_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
