# Generated by Django 5.2.7 on 2025-12-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_org_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='secondary_color',
        ),
    ]
