# Generated by Django 5.2.7 on 2025-12-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_org_colors'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'name'], name='core_contac_organiz_fb70f0_idx'),
        ),
        migrations.AddIndex(
            model_name='orgalertrecipient',
            index=models.Index(fields=['message', 'is_deleted'], name='core_orgale_message_622dec_idx'),
        ),
        migrations.AddIndex(
            model_name='orgalertrecipient',
            index=models.Index(fields=['contact', 'sent_at'], name='core_orgale_contact_9ea780_idx'),
        ),
        migrations.AddIndex(
            model_name='orgalertrecipient',
            index=models.Index(fields=['status', 'retry_count'], name='core_orgale_status_f7262f_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['approval_status', 'created_at'], name='core_organi_approva_a52baa_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmessage',
            index=models.Index(fields=['organization', 'created_at'], name='core_orgmes_organiz_0b17f1_idx'),
        ),
    ]
