# Generated by Django 5.2.7 on 2025-12-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='hubtel_sender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
