# Generated by Django 6.0 on 2025-12-31 18:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_increase_sender_ids_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='balance',
            new_name='sms_credit_balance',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='clicksend_api_key',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='clicksend_username',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hubtel_api_key',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hubtel_api_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hubtel_client_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hubtel_client_secret',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hubtel_sender_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='sender_id',
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the sender', max_length=100)),
                ('sender_id', models.CharField(help_text='The actual sender ID/number', max_length=255, unique=True)),
                ('sender_type', models.CharField(choices=[('numeric', 'Numeric'), ('alphanumeric', 'Alphanumeric')], max_length=20)),
                ('provider', models.CharField(choices=[('hubtel', 'Hubtel'), ('clicksend', 'ClickSend')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('hubtel_api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('hubtel_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hubtel_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('hubtel_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('clicksend_username', models.CharField(blank=True, max_length=100, null=True)),
                ('clicksend_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance with the SMS provider', max_digits=10)),
                ('total_sms_sent', models.PositiveIntegerField(default=0, help_text='Total SMS sent through this sender')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_sender_status_5375ee_idx'), models.Index(fields=['provider'], name='core_sender_provide_60373e_idx'), models.Index(fields=['sender_type'], name='core_sender_sender__316161_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sender_created', 'Sender Created'), ('sender_updated', 'Sender Updated'), ('sender_deleted', 'Sender Deleted'), ('sender_assigned', 'Sender Assigned'), ('sender_unassigned', 'Sender Unassigned'), ('org_credit_added', 'Organization Credit Added'), ('org_credit_deducted', 'Organization Credit Deducted'), ('sms_sent', 'SMS Sent'), ('sms_failed', 'SMS Failed'), ('gateway_balance_low', 'Gateway Balance Low')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sender')),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'), models.Index(fields=['organization', 'created_at'], name='core_auditl_organiz_c79039_idx'), models.Index(fields=['sender', 'created_at'], name='core_auditl_sender__bc09c8_idx'), models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx')],
            },
        ),
        migrations.CreateModel(
            name='SenderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sender')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'is_active'], name='core_sender_organiz_2c676a_idx'), models.Index(fields=['sender', 'is_active'], name='core_sender_sender__390f44_idx')],
                'unique_together': {('sender', 'organization')},
            },
        ),
    ]
