# Generated by Django 5.2.7 on 2026-01-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_balance_organization_sms_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason for banning the organization', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='banned',
            field=models.BooleanField(default=False, help_text='Whether this organization is banned from the platform'),
        ),
        migrations.AddField(
            model_name='organization',
            name='banned_at',
            field=models.DateTimeField(blank=True, help_text='When the organization was banned', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='banned_by',
            field=models.ForeignKey(blank=True, help_text='User who banned this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
