"""
Django settings for school_alert_system project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
from dotenv import load_dotenv
import os
from decimal import Decimal
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Secret key - read from environment in production
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-t0m_^1qsaw936&_8k522onzs@eo3woi29^s2$7#*1_=u08yrh8')

# DEBUG should be False in production. Read from env for Render deployment.
DEBUG = os.environ.get('DEBUG', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}

# ALLOWED_HOSTS can be provided via env var (comma-separated). Default to all for local dev.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CurrentTenantMiddleware',
]

ROOT_URLCONF = 'school_alert_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Expose tenant branding and convenience variables to all templates
                'core.context_processors.tenant_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_alert_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from django.core.exceptions import ImproperlyConfigured

# Production-first database configuration: prefer DATABASE_URL (Postgres).
# Behavior:
# - If DATABASE_URL is set, use dj_database_url to parse it (Postgres, etc.).
# - If DATABASE_URL is not set and DEBUG is True (local dev), fall back to sqlite.
# - If DATABASE_URL is not set and DEBUG is False (production), raise an error so
#   deployments fail fast and you don't accidentally run with sqlite in production.
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    try:
        import dj_database_url

        conn_max_age = int(os.environ.get('CONN_MAX_AGE', '600'))
        ssl_req_str = os.environ.get('DB_SSL_REQUIRE')
        if ssl_req_str is None:
            ssl_req = True
        else:
            ssl_req = ssl_req_str.strip().lower() in {'1', 'true', 'yes', 'on'}
        DATABASES = {
            'default': dj_database_url.parse(
                DATABASE_URL,
                conn_max_age=conn_max_age,
                ssl_require=ssl_req,
            )
        }
    except Exception as exc:  # pragma: no cover - should be visible at startup
        raise ImproperlyConfigured(f"dj_database_url is required when DATABASE_URL is set: {exc}")
else:
    # No DATABASE_URL provided
    if DEBUG:
        # Local development: sqlite fallback
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    else:
        # Production must provide DATABASE_URL
        raise ImproperlyConfigured(
            "DATABASE_URL is not set. For production deployments set DATABASE_URL to your Postgres connection string."
        )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Directory where `collectstatic` will collect static files for production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use WhiteNoise to serve static files in production (works well on Render)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Security settings for production. Applied when DEBUG is False.
if not DEBUG:
    # HTTP Strict Transport Security - set a short default; increase once verified
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '60'))
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').strip().lower() in {'1', 'true', 'yes'}
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# Media files (uploaded logos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration: prefer SMTP when EMAIL_HOST is set, otherwise use console backend for dev
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}
else:
    # Development-friendly default: print password reset emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Custom user model for multi-tenancy
AUTH_USER_MODEL = 'core.User'

# Hubtel (local SMS holder) configuration
# HUBTEL_API_URL should point to your local Hubtel-compatible service (e.g. http://localhost:9000)
HUBTEL_API_URL = os.environ.get('HUBTEL_API_URL') or os.environ.get('CLICKSEND_API_URL')
HUBTEL_API_KEY = os.environ.get('HUBTEL_API_KEY') or os.environ.get('CLICKSEND_API_KEY')

# Optional Hubtel client credentials (preferred for Hubtel API)
HUBTEL_CLIENT_ID = os.environ.get('HUBTEL_CLIENT_ID')
HUBTEL_CLIENT_SECRET = os.environ.get('HUBTEL_CLIENT_SECRET')

# Hubtel dry-run mode: kept for compatibility but defaults to False (live sends by default)
def _env_bool(name: str, default: bool) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "yes", "on"}

# Default to False so Hubtel calls are live unless explicitly disabled
HUBTEL_DRY_RUN = _env_bool('HUBTEL_DRY_RUN', default=False)

# Optional default numeric sender used for testing (e.g. 233530422137)
# Set via environment variable HUBTEL_DEFAULT_SENDER if you want Hubtel calls
# to include a numeric 'from' when tenant.sender_id is not provided.
HUBTEL_DEFAULT_SENDER = os.environ.get('HUBTEL_DEFAULT_SENDER')
# Webhook secret used to verify incoming Hubtel delivery receipts (HMAC-SHA256)
HUBTEL_WEBHOOK_SECRET = os.environ.get('HUBTEL_WEBHOOK_SECRET')

# Optional Google reCAPTCHA settings
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY')
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY')

# Legacy Twilio/ClickSend credentials (kept for backwards compat but Hubtel is preferred)
# TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID')
# TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN')

# Paystack payment gateway settings
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY')
PAYSTACK_BASE_URL = 'https://api.paystack.co'

# SMS Pricing and Billing Configuration
# Cost per SMS from providers (what you pay)
SMS_PROVIDER_COST = Decimal(os.environ.get('SMS_PROVIDER_COST', '0.03'))  # Default 0.03 GHS

# What you charge customers per SMS (must be > SMS_PROVIDER_COST for profit)
SMS_CUSTOMER_RATE = Decimal(os.environ.get('SMS_CUSTOMER_RATE', '0.05'))  # Default 0.05 GHS

# Minimum balance required before allowing sends
SMS_MIN_BALANCE = Decimal(os.environ.get('SMS_MIN_BALANCE', '1.00'))  # Default 1.00 GHS

# Profit margin per SMS = SMS_CUSTOMER_RATE - SMS_PROVIDER_COST
